# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, functions):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 0, 0, 1, 2)
        self.pushSearch = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushSearch.setFont(font)
        self.pushSearch.setObjectName("pushSearch")
        self.gridLayout_2.addWidget(self.pushSearch, 1, 1, 1, 1)
        self.tab_main = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_main.setFont(font)
        self.tab_main.setObjectName("tab_main")
        self.tab_project = QtWidgets.QWidget()
        self.tab_project.setObjectName("tab_project")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_8.setGeometry(QtCore.QRect(577, 30, 88, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_9.setGeometry(QtCore.QRect(435, 30, 135, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_10.setGeometry(QtCore.QRect(97, 30, 111, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_11.setGeometry(QtCore.QRect(310, 30, 118, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setTristate(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_12.setGeometry(QtCore.QRect(215, 30, 88, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_project)
        self.checkBox_2.setGeometry(QtCore.QRect(2, 30, 88, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.tab_main.addTab(self.tab_project, "")
        self.tab_topic = QtWidgets.QWidget()
        self.tab_topic.setObjectName("tab_topic")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_topic)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 0, 5, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 0, 4, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 3, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_15.sizePolicy().hasHeightForWidth())
        self.checkBox_15.setSizePolicy(sizePolicy)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 1, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_16.sizePolicy().hasHeightForWidth())
        self.checkBox_16.setSizePolicy(sizePolicy)
        self.checkBox_16.setTristate(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_13.sizePolicy().hasHeightForWidth())
        self.checkBox_13.setSizePolicy(sizePolicy)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 2, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_topic)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.tab_main.addTab(self.tab_topic, "")
        self.tab_work = QtWidgets.QWidget()
        self.tab_work.setObjectName("tab_work")
        self.checkBox_14 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_14.setGeometry(QtCore.QRect(215, 30, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_14.sizePolicy().hasHeightForWidth())
        self.checkBox_14.setSizePolicy(sizePolicy)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_17.setGeometry(QtCore.QRect(435, 30, 135, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_17.sizePolicy().hasHeightForWidth())
        self.checkBox_17.setSizePolicy(sizePolicy)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_18.setGeometry(QtCore.QRect(520, 30, 103, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_18.sizePolicy().hasHeightForWidth())
        self.checkBox_18.setSizePolicy(sizePolicy)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_19.setGeometry(QtCore.QRect(130, 30, 76, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_19.sizePolicy().hasHeightForWidth())
        self.checkBox_19.setSizePolicy(sizePolicy)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_20.setGeometry(QtCore.QRect(2, 30, 122, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_20.sizePolicy().hasHeightForWidth())
        self.checkBox_20.setSizePolicy(sizePolicy)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_work)
        self.checkBox_21.setGeometry(QtCore.QRect(310, 30, 118, 25))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_21.sizePolicy().hasHeightForWidth())
        self.checkBox_21.setSizePolicy(sizePolicy)
        self.checkBox_21.setTristate(False)
        self.checkBox_21.setObjectName("checkBox_21")
        self.tab_main.addTab(self.tab_work, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setObjectName("tab_misc")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_misc)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_22.sizePolicy().hasHeightForWidth())
        self.checkBox_22.setSizePolicy(sizePolicy)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_3.addWidget(self.checkBox_22, 0, 0, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_27.sizePolicy().hasHeightForWidth())
        self.checkBox_27.setSizePolicy(sizePolicy)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_3.addWidget(self.checkBox_27, 0, 1, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_26.sizePolicy().hasHeightForWidth())
        self.checkBox_26.setSizePolicy(sizePolicy)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 0, 2, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_24.sizePolicy().hasHeightForWidth())
        self.checkBox_24.setSizePolicy(sizePolicy)
        self.checkBox_24.setTristate(False)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 0, 3, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_23.sizePolicy().hasHeightForWidth())
        self.checkBox_23.setSizePolicy(sizePolicy)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 0, 4, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.tab_misc)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_25.sizePolicy().hasHeightForWidth())
        self.checkBox_25.setSizePolicy(sizePolicy)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 0, 5, 1, 1)
        self.tab_main.addTab(self.tab_misc, "")
        self.tab_task = QtWidgets.QWidget()
        self.tab_task.setObjectName("tab_task")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_task)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_28 = QtWidgets.QCheckBox(self.tab_task)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_28.sizePolicy().hasHeightForWidth())
        self.checkBox_28.setSizePolicy(sizePolicy)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_4.addWidget(self.checkBox_28, 0, 0, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.tab_task)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_30.sizePolicy().hasHeightForWidth())
        self.checkBox_30.setSizePolicy(sizePolicy)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_4.addWidget(self.checkBox_30, 0, 1, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.tab_task)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_33.sizePolicy().hasHeightForWidth())
        self.checkBox_33.setSizePolicy(sizePolicy)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_4.addWidget(self.checkBox_33, 0, 2, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.tab_task)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_29.sizePolicy().hasHeightForWidth())
        self.checkBox_29.setSizePolicy(sizePolicy)
        self.checkBox_29.setTristate(False)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_4.addWidget(self.checkBox_29, 0, 3, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.tab_task)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_32.sizePolicy().hasHeightForWidth())
        self.checkBox_32.setSizePolicy(sizePolicy)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_4.addWidget(self.checkBox_32, 0, 4, 1, 1)
        self.tab_main.addTab(self.tab_task, "")
        self.tab_tool = QtWidgets.QWidget()
        self.tab_tool.setObjectName("tab_tool")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_tool)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_31 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_31.sizePolicy().hasHeightForWidth())
        self.checkBox_31.setSizePolicy(sizePolicy)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_5.addWidget(self.checkBox_31, 0, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_35.sizePolicy().hasHeightForWidth())
        self.checkBox_35.setSizePolicy(sizePolicy)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_5.addWidget(self.checkBox_35, 0, 1, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_38.sizePolicy().hasHeightForWidth())
        self.checkBox_38.setSizePolicy(sizePolicy)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout_5.addWidget(self.checkBox_38, 0, 2, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_34.sizePolicy().hasHeightForWidth())
        self.checkBox_34.setSizePolicy(sizePolicy)
        self.checkBox_34.setTristate(False)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_5.addWidget(self.checkBox_34, 0, 3, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_37.sizePolicy().hasHeightForWidth())
        self.checkBox_37.setSizePolicy(sizePolicy)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout_5.addWidget(self.checkBox_37, 0, 4, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_36.sizePolicy().hasHeightForWidth())
        self.checkBox_36.setSizePolicy(sizePolicy)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_5.addWidget(self.checkBox_36, 0, 5, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_41.sizePolicy().hasHeightForWidth())
        self.checkBox_41.setSizePolicy(sizePolicy)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout_5.addWidget(self.checkBox_41, 1, 0, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_40.sizePolicy().hasHeightForWidth())
        self.checkBox_40.setSizePolicy(sizePolicy)
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout_5.addWidget(self.checkBox_40, 1, 1, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_43.sizePolicy().hasHeightForWidth())
        self.checkBox_43.setSizePolicy(sizePolicy)
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout_5.addWidget(self.checkBox_43, 1, 2, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(self.tab_tool)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_42.sizePolicy().hasHeightForWidth())
        self.checkBox_42.setSizePolicy(sizePolicy)
        self.checkBox_42.setTristate(False)
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout_5.addWidget(self.checkBox_42, 1, 3, 1, 1)
        self.tab_main.addTab(self.tab_tool, "")
        self.tab_file = QtWidgets.QWidget()
        self.tab_file.setObjectName("tab_file")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_file)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox_87 = QtWidgets.QCheckBox(self.tab_file)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_87.sizePolicy().hasHeightForWidth())
        self.checkBox_87.setSizePolicy(sizePolicy)
        self.checkBox_87.setObjectName("checkBox_87")
        self.gridLayout_10.addWidget(self.checkBox_87, 0, 0, 1, 1)
        self.checkBox_85 = QtWidgets.QCheckBox(self.tab_file)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_85.sizePolicy().hasHeightForWidth())
        self.checkBox_85.setSizePolicy(sizePolicy)
        self.checkBox_85.setObjectName("checkBox_85")
        self.gridLayout_10.addWidget(self.checkBox_85, 0, 1, 1, 1)
        self.checkBox_89 = QtWidgets.QCheckBox(self.tab_file)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_89.sizePolicy().hasHeightForWidth())
        self.checkBox_89.setSizePolicy(sizePolicy)
        self.checkBox_89.setObjectName("checkBox_89")
        self.gridLayout_10.addWidget(self.checkBox_89, 0, 2, 1, 1)
        self.checkBox_88 = QtWidgets.QCheckBox(self.tab_file)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_88.sizePolicy().hasHeightForWidth())
        self.checkBox_88.setSizePolicy(sizePolicy)
        self.checkBox_88.setTristate(False)
        self.checkBox_88.setObjectName("checkBox_88")
        self.gridLayout_10.addWidget(self.checkBox_88, 0, 3, 1, 1)
        self.checkBox_90 = QtWidgets.QCheckBox(self.tab_file)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_90.sizePolicy().hasHeightForWidth())
        self.checkBox_90.setSizePolicy(sizePolicy)
        self.checkBox_90.setObjectName("checkBox_90")
        self.gridLayout_10.addWidget(self.checkBox_90, 0, 4, 1, 1)
        self.tab_main.addTab(self.tab_file, "")
        self.tab_need = QtWidgets.QWidget()
        self.tab_need.setObjectName("tab_need")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_need)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.checkBox_91 = QtWidgets.QCheckBox(self.tab_need)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_91.sizePolicy().hasHeightForWidth())
        self.checkBox_91.setSizePolicy(sizePolicy)
        self.checkBox_91.setObjectName("checkBox_91")
        self.gridLayout_11.addWidget(self.checkBox_91, 0, 0, 1, 1)
        self.checkBox_86 = QtWidgets.QCheckBox(self.tab_need)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_86.sizePolicy().hasHeightForWidth())
        self.checkBox_86.setSizePolicy(sizePolicy)
        self.checkBox_86.setObjectName("checkBox_86")
        self.gridLayout_11.addWidget(self.checkBox_86, 0, 1, 1, 1)
        self.checkBox_94 = QtWidgets.QCheckBox(self.tab_need)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_94.sizePolicy().hasHeightForWidth())
        self.checkBox_94.setSizePolicy(sizePolicy)
        self.checkBox_94.setObjectName("checkBox_94")
        self.gridLayout_11.addWidget(self.checkBox_94, 0, 2, 1, 1)
        self.checkBox_92 = QtWidgets.QCheckBox(self.tab_need)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_92.sizePolicy().hasHeightForWidth())
        self.checkBox_92.setSizePolicy(sizePolicy)
        self.checkBox_92.setTristate(False)
        self.checkBox_92.setObjectName("checkBox_92")
        self.gridLayout_11.addWidget(self.checkBox_92, 0, 3, 1, 1)
        self.checkBox_93 = QtWidgets.QCheckBox(self.tab_need)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.checkBox_93.sizePolicy().hasHeightForWidth())
        self.checkBox_93.setSizePolicy(sizePolicy)
        self.checkBox_93.setObjectName("checkBox_93")
        self.gridLayout_11.addWidget(self.checkBox_93, 0, 4, 1, 1)
        self.tab_main.addTab(self.tab_need, "")
        self.gridLayout_2.addWidget(self.tab_main, 1, 0, 2, 1)
        self.pushExit_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushExit_2.setFont(font)
        self.pushExit_2.setObjectName("pushExit_2")
        self.gridLayout_2.addWidget(self.pushExit_2, 2, 1, 1, 1)
        self.pushSearch.raise_()
        self.pushExit_2.raise_()
        self.tab_main.raise_()
        self.plainTextEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushSearch.setText(_translate("MainWindow", "Search"))
        self.checkBox_8.setText(_translate("MainWindow", "Inferred"))
        self.checkBox_9.setText(_translate("MainWindow", "Undemarcated"))
        self.checkBox_10.setText(_translate("MainWindow", "Enviroment"))
        self.checkBox_11.setText(_translate("MainWindow", "Demarcated"))
        self.checkBox_12.setText(_translate("MainWindow", "Parking"))
        self.checkBox_2.setText(_translate("MainWindow", "Project"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_project), _translate("MainWindow", "Project"))
        self.checkBox_6.setText(_translate("MainWindow", "Code"))
        self.checkBox_3.setText(_translate("MainWindow", "FrameWork"))
        self.checkBox_4.setText(_translate("MainWindow", "FrontEnd"))
        self.checkBox_15.setText(_translate("MainWindow", "Python"))
        self.checkBox_16.setText(_translate("MainWindow", "DataBase"))
        self.checkBox_13.setText(_translate("MainWindow", "Java"))
        self.checkBox_5.setText(_translate("MainWindow", "BackEnd"))
        self.checkBox_7.setText(_translate("MainWindow", "Manual"))
        self.checkBox.setText(_translate("MainWindow", "Automate"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_topic), _translate("MainWindow", "Topic"))
        self.checkBox_14.setText(_translate("MainWindow", "Meeting"))
        self.checkBox_17.setText(_translate("MainWindow", "Review"))
        self.checkBox_18.setText(_translate("MainWindow", "Ready4Qa"))
        self.checkBox_19.setText(_translate("MainWindow", "Defect"))
        self.checkBox_20.setText(_translate("MainWindow", "Requirement"))
        self.checkBox_21.setText(_translate("MainWindow", "Regression"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_work), _translate("MainWindow", "Work"))
        self.checkBox_22.setText(_translate("MainWindow", "AddWorkFlow"))
        self.checkBox_27.setText(_translate("MainWindow", "KnowHow"))
        self.checkBox_26.setText(_translate("MainWindow", "Meeting"))
        self.checkBox_24.setText(_translate("MainWindow", "HowTo"))
        self.checkBox_23.setText(_translate("MainWindow", "Directive"))
        self.checkBox_25.setText(_translate("MainWindow", "PlanForTheDay"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_misc), _translate("MainWindow", "Misc."))
        self.checkBox_28.setText(_translate("MainWindow", "Starting"))
        self.checkBox_30.setText(_translate("MainWindow", "DataConsistency"))
        self.checkBox_33.setText(_translate("MainWindow", "e2e"))
        self.checkBox_29.setText(_translate("MainWindow", "Turnover"))
        self.checkBox_32.setText(_translate("MainWindow", "DwellTime"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_task), _translate("MainWindow", "Task"))
        self.checkBox_31.setText(_translate("MainWindow", "Looker"))
        self.checkBox_35.setText(_translate("MainWindow", "IntelliJ"))
        self.checkBox_38.setText(_translate("MainWindow", "PyCharm"))
        self.checkBox_34.setText(_translate("MainWindow", "Github"))
        self.checkBox_37.setText(_translate("MainWindow", "Jira"))
        self.checkBox_36.setText(_translate("MainWindow", "Postman"))
        self.checkBox_41.setText(_translate("MainWindow", "DcOs"))
        self.checkBox_40.setText(_translate("MainWindow", "Kafka"))
        self.checkBox_43.setText(_translate("MainWindow", "Allure"))
        self.checkBox_42.setText(_translate("MainWindow", "Jenkins"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_tool), _translate("MainWindow", "Tool"))
        self.checkBox_87.setText(_translate("MainWindow", "File"))
        self.checkBox_85.setText(_translate("MainWindow", "Xlsx"))
        self.checkBox_89.setText(_translate("MainWindow", "Link"))
        self.checkBox_88.setText(_translate("MainWindow", "LogIn"))
        self.checkBox_90.setText(_translate("MainWindow", "Letter"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_file), _translate("MainWindow", "File"))
        self.checkBox_91.setText(_translate("MainWindow", "ToDo"))
        self.checkBox_86.setText(_translate("MainWindow", "NeedToCheck"))
        self.checkBox_94.setText(_translate("MainWindow", "Done"))
        self.checkBox_92.setText(_translate("MainWindow", "ToDo"))
        self.checkBox_93.setText(_translate("MainWindow", "Learning"))
        self.tab_main.setTabText(self.tab_main.indexOf(
            self.tab_need), _translate("MainWindow", "Need to do"))
        self.pushExit_2.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

        self.pushExit_2.clicked.connect(functions.close_application)
        self.actionOpen.triggered.connect(functions.file_open)
        self.pushSearch.clicked.connect(self.empty_editor)

    def empty_editor(self):
        # print(self.__dict__)
        self.plainTextEdit.clear()
        functions.searching()


if __name__ == "__main__":
    import sys
    from functions import Functions
    functions = Functions()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, functions)
    MainWindow.show()
    sys.exit(app.exec_())
